/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import sistemasolar.sg.SistemaSolarSG;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author borja & balti
 */

public class Control extends JFrame {

    private SistemaSolarSG universe;

    public Control(SistemaSolarSG anUniverse) {
        initComponents();
        
        universe = anUniverse ;

        setTitle ("Control") ;
        setLocation (650, 100) ;
    
        addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                exit (0);
            }
        });

        repaint();
    }

    public void exit (int status) {
        System.exit (status);
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    
    private void initComponents(){

        buttonGroup3 = new javax.swing.ButtonGroup() ;
        jb_exit = new javax.swing.JButton() ;
        jPanel1 = new javax.swing.JPanel() ;
        Global = new javax.swing.JRadioButton() ;
        Nave = new javax.swing.JRadioButton() ;
        Luna = new javax.swing.JRadioButton() ;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE) ;

        jb_exit.setMnemonic('X') ;
        jb_exit.setText("Salir") ;
        
        jb_exit.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                jb_exitActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Vistas")) ;

        buttonGroup3.add(Global) ;
        Global.setSelected(true) ;
        Global.setText("Global") ;
        Global.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                GlobalActionPerformed(evt);
            }
        });

        buttonGroup3.add(Nave) ;
        Nave.setText("Nave") ;
        Nave.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                NaveActionPerformed(evt);
            }
        });

        buttonGroup3.add(Luna) ;
        Luna.setText("Luna") ;
        Luna.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                LunaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1) ;
        jPanel1.setLayout(jPanel1Layout) ;
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Luna)
                    .addComponent(Nave)
                    .addComponent(Global))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Global)
                .addGap(18, 18, 18)
                .addComponent(Nave)
                .addGap(18, 18, 18)
                .addComponent(Luna)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jb_exit)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jb_exit)
                .addContainerGap())
        );

        pack();
    }

    private void jb_exitActionPerformed(java.awt.event.ActionEvent evt){
        exit(0) ;
    }

    private void NaveActionPerformed(java.awt.event.ActionEvent evt){
        if(Nave.isSelected()){
            universe.selectViewNave() ;
        }
    }

    private void LunaActionPerformed(java.awt.event.ActionEvent evt){
        if(Luna.isSelected()){
            universe.selectViewLuna() ;
        }
    }

    private void GlobalActionPerformed(java.awt.event.ActionEvent evt){
        if(Global.isSelected()){
            universe.selectViewPerspectiva() ;
        }
    }

    private javax.swing.JRadioButton Global;
    private javax.swing.JRadioButton Luna;
    private javax.swing.JRadioButton Nave;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_exit;
}
